module.exports = {
  content: ['./src/**/*.{html,js}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontSize: {
        custom: 'var(--font-size-custom)',
      },
      colors: {
        primary: 'var(--colors-primary)',
        secondary: 'var(--colors-secondary)',
        success: 'var(--colors-success)',
        warning: 'var(--colors-warning)',
        danger: 'var(--colors-danger)',
        black: 'var(--colors-black)',
        white: 'var(--colors-white)',
        muted: 'var(--colors-muted)',
        background1: 'var(--colors-background1)',
        background2: 'var(--colors-background2)',
        'background-deleted-row': 'var(--colors-background-deleted-row)',
        'tw-white': 'var(--colors-tw-white)',
        'tw-black': 'var(--colors-tw-black)',
        'scrollbar-background': 'var(--colors-scrollbar-background)',
        'scrollbar-thumb': 'var(--colors-scrollbar-thumb)',
      },
      variables: {
        DEFAULT: {
          colors: {
            primary: '#21c7a3',
            secondary: '#397af2',
            success: '#17c671',
            danger: '#c4183c',
            warning: '#ffb400',
            background1: '#eff1f6',
            background2: '#F9FAFC',
            'background-deleted-row': '#ffe6e6',
            'background-rejected-row': '#ffe6e6',
            'background-completed-row': '#eeffe6',
            'background-recorded-row': '#e6ffe6',
            'background-selected-row': '#e0f6ff',
            'background-incompleted-row': '#fffae6',
            'background-header-row': '#f9f9f9',
            'tw-white': '#F9FAFC',
            'tw-black': '#293756',
            white: '#FFFFFF',
            black: '#000000',
            muted: '#868e96',
            'scrollbar-background': '#397af2',
            'scrollbar-thumb': '#21c7a3',
          },
          font_size_custom: '1.7rem',
        },
        '.card': {
          font_size_custom: '2rem',
        },
      },
      darkVariables: {
        DEFAULT: {
          colors: {
            primary: '#21c7a3',
            secondary: '#397af2',
            success: '#17c671',
            warning: '#ffb400',
            danger: '#c4183c',
            background1: '#111622',
            background2: '#151c29',
            'background-deleted-row': '#410808',
            'background-rejected-row': '#410808',
            'background-completed-row': '#153706',
            'background-recorded-row': '#074607',
            'background-selected-row': '#0a3c50',
            'background-incompleted-row': '#4e410e',
            'background-header-row': '#481212',
            white: '#000000',
            black: '#FFFFFF',
            muted: '#868e96',
            'tw-white': '#324267',
            'tw-black': '#d4d9dd',
            'scrollbar-background': '#397af2',
            'scrollbar-thumb': '#21c7a3',
          },
          font_size_custom: '1rem',
        },
        '.card': {
          font_size_custom: '1.3rem',
        },
      },
    },
  },
  variants: {},
  plugins: [
    require('@mertasan/tailwindcss-variables')({
      darkToRoot: true,
    }),
  ],
};
