export const routes = {
  LOGIN: '/auth/login',
  SPLASH: '/splash',
  SIGNUP: '/auth/signup',
  RESET_PASSWORD: '/auth/reset-password',
  VERIFICATION: '/auth/verification',
  DASHBOARD: '/',
  PROFILE: '/profile',
  WEIGHT: '/milk/weight',
  ABOUT: '/about',
  MILK_QC: '/milk/milk-qc',
  MILK_DAILY_TEST: '/milk/milk-daily-test',
  MILK_QC_REPORT: '/milk/milk-qc-report',
  MILK_DAILY_REPORT: '/milk/milk-daily-report',
  DAILY_SUMMARY_REPORT: '/milk/daily-summary-report',
  PRICING: '/milk/pricing',
  ALL_USERS: '/persons/users',
  PENDING_USERS: '/persons/users_pending',
  EMPLOYEES: '/persons/employees',
  MEMBERS: '/persons/members',
  DELIVERY: 'DeliveyStackScreen',
  EXCEL_UPLOAD: '/utils/upload-data-from-excel-file',
  CHECK_DATA: '/developer/check_data',
  SCREEN1: 'screen1',
  SCREEN2: 'screen2',
};
