export const routes = {
  LOGIN: '/auth/login',
  SPLASH: '/splash',
  SIGNUP: '/auth/signup',
  RESET_PASSWORD: '/auth/reset-password',
  VERIFICATION: '/auth/verification',
  DASHBOARD: '/',
  PROFILE: '/profile',
  FAVORITES: 'FavoritesTabScreen',
  BASKETTAB: 'BasketTabScreen',
  RESTAURANT: 'RestaurantTabScreen',
  HOME: 'HomeStackScreen',
  DETAIL: 'DetailStackScreen',
  BASKET: 'BasketStackScreen',
  CHECKOUT: 'CheckoutStackScreen',
  DELIVERY: 'DeliveyStackScreen',
  RESTAURANTDETAIL: 'RestaurantDetailStackScreen',
  SCREEN1: 'screen1',
  SCREEN2: 'screen2',
};
