export const routes = {
  LOGIN: '/auth/login',
  SPLASH: '/splash',
  SIGNUP: '/auth/signup',
  RESET_PASSWORD: '/auth/reset-password',
  VERIFICATION: '/auth/verification',
  DASHBOARD: '/',
  PROFILE: '/profile',
  WEIGHT: '/milk/weight',
  ABOUT: '/about',
  RESTAURANT: 'RestaurantTabScreen',
  HOME: 'HomeStackScreen',
  DETAIL: 'DetailStackScreen',
  BASKET: 'BasketStackScreen',
  CHECKOUT: 'CheckoutStackScreen',
  DELIVERY: 'DeliveyStackScreen',
  EXCEL_UPLOAD: '/utils/upload-data-from-excel-file',
  SCREEN1: 'screen1',
  SCREEN2: 'screen2',
};
